<?php

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DatabaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $this->call([BarcodesTableSeeder::class,
                    PermissionsTableSeeder::class,
                    CurrenciesTableSeeder::class
                    ]);

        // Seeder para la tabla invoice_schemes
        DB::table('invoice_schemes')->insert([
            'business_id' => 1,
            'name' => 'Default',
            'scheme_type' => 'blank',
            'prefix' => '',
            'start_number' => 1,
            'invoice_count' => 2146,
            'total_digits' => 4,
            'is_default' => 1,
            'created_at' => Carbon::create('2022', '01', '16', '02', '12', '08'),
            'updated_at' => Carbon::create('2024', '08', '08', '13', '23', '33'),
        ]);

        // Seeder para la tabla invoice_layouts
        DB::table('invoice_layouts')->insert([
            'name' => 'Default',
            'header_text' => null,
            'invoice_no_prefix' => 'Invoice No.',
            'quotation_no_prefix' => null,
            'invoice_heading' => 'Invoice',
            'sub_heading_line1' => null,
            'sub_heading_line2' => null,
            'sub_heading_line3' => null,
            'sub_heading_line4' => null,
            'sub_heading_line5' => null,
            'invoice_heading_not_paid' => null,
            'invoice_heading_paid' => null,
            'quotation_heading' => null,
            'sub_total_label' => 'Subtotal',
            'discount_label' => 'Discount',
            'tax_label' => 'Tax',
            'total_label' => 'Total',
            'total_due_label' => 'Total Due',
            'paid_label' => 'Total Paid',
            'show_client_id' => 0,
            'client_id_label' => null,
            'client_tax_label' => null,
            'date_label' => 'Date',
            'date_time_format' => 'd-m-Y',
            'show_time' => 1,
            'show_brand' => 0,
            'show_sku' => 0,
            'show_cat_code' => 0,
            'show_expiry' => 0,
            'show_lot' => 0,
            'show_image' => 0,
            'show_sale_description' => 0,
            'sales_person_label' => null,
            'show_sales_person' => 0,
            'table_product_label' => 'Servicio',
            'table_qty_label' => 'Cantidad',
            'table_unit_price_label' => 'Pr. Unit.',
            'table_subtotal_label' => 'Subtotal',
            'cat_code_label' => null,
            'logo' => null,
            'show_logo' => 0,
            'show_business_name' => 1,
            'show_location_name' => 0,
            'show_landmark' => 1,
            'show_city' => 1,
            'show_state' => 1,
            'show_zip_code' => 0,
            'show_country' => 1,
            'show_mobile_number' => 0,
            'show_alternate_number' => 0,
            'show_email' => 0,
            'show_tax_1' => 1,
            'show_tax_2' => 1,
            'show_barcode' => 0,
            'show_payments' => 1,
            'show_customer' => 1,
            'customer_label' => 'Customer',
            'highlight_color' => '#000000',
            'footer_text' => '<p style="text-align:center"><span style="font-size:14px">Muchas gracias por elegirnos, ¡te esperamos pronto!</span></p>',
            'module_info' => null,
            'is_default' => 1,
            'business_id' => 1,
            'design' => 'classic',
            'cn_heading' => null,
            'cn_no_label' => null,
            'cn_amount_label' => null,
            'table_tax_headings' => null,
            'show_previous_bal' => 0,
            'prev_bal_label' => null,
            'product_custom_fields' => null,
            'contact_custom_fields' => null,
            'location_custom_fields' => null,
            'created_at' => Carbon::create('2022', '01', '16', '02', '12', '08'),
            'updated_at' => Carbon::create('2022', '12', '22', '09', '42', '13'),
        ]);

        // Seeder para la tabla contacts
        DB::table('contacts')->insert([
            'business_id' => 1,
            'type' => 'customer',
            'supplier_business_name' => null,
            'name' => 'CONSUMIDOR FINAL',
            'email' => null,
            'contact_id' => 'CO0004',
            'tipo_doc' => null,
            'tax_number' => null,
            'iva' => 'CONSUMIDOR FINAL',
            'city' => null,
            'state' => null,
            'country' => null,
            'landmark' => null,
            'mobile' => '0',
            'landline' => null,
            'alternate_number' => null,
            'pay_term_number' => null,
            'pay_term_type' => null,
            'credit_limit' => null,
            'created_by' => 1,
            'is_default' => 1,
            'customer_group_id' => null,
            'custom_field1' => null,
            'custom_field2' => null,
            'custom_field3' => null,
            'custom_field4' => null,
            'deleted_at' => null,
            'created_at' => Carbon::create('2022', '03', '15', '13', '35', '29'),
            'updated_at' => Carbon::create('2022', '05', '04', '08', '45', '10'),
        ]);

        // Seeder para la tabla business_locations
        DB::table('business_locations')->insert([
            'business_id' => 1,
            'location_id' => 'BL0001',
            'name' => 'Hudson',
            'razon_social' => 'hudson',
            'landmark' => 'Ayacucho 2451',
            'country' => 'Argentina',
            'state' => 'Misiones',
            'city' => 'Posadas',
            'zip_code' => '3300',
            'invoice_scheme_id' => 1,
            'invoice_layout_id' => 1,
            'print_receipt_on_invoice' => 1,
            'receipt_printer_type' => 'browser',
            'printer_id' => null,
            'mobile' => '3764684556',
            'alternate_number' => '555',
            'email' => null,
            'website' => 'majestetica.com.ar',
            'tax_label_1' => 'RESPONSABLE INSCRIPTO',
            'cuit' => '33715007369',
            'punto_venta' => 13,
            'url_cert' => 'storage/app/public/1/1_cert.crt',
            'url_key' => 'storage/app/public/1/1_key.key',
            'tax_label_2' => 'Ingresos Brutos',
            'tax_number_2' => '33715007369',
            'afip_start_date' => Carbon::create('2023', '01', '12'),
            'custom_field1' => null,
            'custom_field2' => null,
            'custom_field3' => null,
            'custom_field4' => null,
            'deleted_at' => null,
            'created_at' => Carbon::create('2022', '01', '16', '02', '12', '08'),
            'updated_at' => Carbon::create('2024', '04', '30', '09', '34', '17'),
        ]);

        // Seeder para la tabla business
        DB::table('business')->insert([
            'name' => 'Cristaldo',
            'business_name' => null,
            'currency_id' => 4,
            'start_date' => Carbon::create('2022', '01', '15'),
            'invoice_register_limit' => 150000,
            'invoice_limit_card' => 91000,
            'default_sales_tax' => null,
            'default_profit_percent' => 25.00,
            'owner_id' => 1,
            'time_zone' => 'America/Argentina/Buenos_Aires',
            'fy_start_month' => 1,
            'accounting_method' => 'fifo',
            'default_sales_discount' => null,
            'sell_price_tax' => 'includes',
            'logo' => '1642279328_WhatsApp Image 2021-12-15 at 13.22.03 (2).jpg',
            'sku_prefix' => null,
            'enable_product_expiry' => 0,
            'expiry_type' => 'add_expiry',
            'on_product_expiry' => 'keep_selling',
            'stop_selling_before' => 0,
            'enable_tooltip' => 1,
            'purchase_in_diff_currency' => 0,
            'purchase_currency_id' => null,
            'p_exchange_rate' => 1.000,
            'transaction_edit_days' => 30,
            'stock_expiry_alert_days' => 30,
            'keyboard_shortcuts' => json_encode([
                'pos' => [
                    'express_checkout' => 'shift+e',
                    'pay_n_ckeckout' => 'shift+p',
                    'draft' => 'shift+d',
                    'cancel' => 'shift+c',
                    'recent_product_quantity' => 'f2',
                    'finalize_pay_express' => null,
                    'express_finalize' => null,
                    'edit_discount' => 'shift+i',
                    'edit_order_tax' => 'shift+t',
                    'add_payment_row' => 'shift+r',
                    'finalize_payment' => 'shift+f',
                    'add_new_product' => 'f4',
                    'pago_multiple' => null,
                ]
            ]),
            'pos_settings' => json_encode([
                'allow_overselling' => 1,
                'is_pos_subtotal_editable' => 1,
                'disable_pay_checkout' => 0,
                'disable_draft' => 0,
                'disable_express_checkout' => 0,
                'hide_product_suggestion' => 0,
                'hide_recent_trans' => 0,
                'disable_discount' => 0,
                'disable_order_tax' => 0,
                'pagos_monedas' => 0,
                'check_afip' => 0,
                'modal_cambio' => 0,
            ]),
            'enable_brand' => 1,
            'enable_category' => 1,
            'enable_sub_category' => 1,
            'enable_price_tax' => 1,
            'enable_purchase_status' => 1,
            'enable_lot_number' => 0,
            'default_unit' => null,
            'enable_racks' => 0,
            'enable_row' => 0,
            'enable_position' => 0,
            'enable_editing_product_from_purchase' => 1,
            'sales_cmsn_agnt' => null,
            'item_addition_method' => 0,
            'enable_inline_tax' => 0,
            'currency_symbol_placement' => 'before',
            'enabled_modules' => json_encode([
                'purchase' => 'PO',
                'purchase_return' => null,
                'stock_transfer' => 'ST',
                'stock_adjustment' => 'SA',
                'sell_return' => 'CN',
                'expense' => 'EP',
                'contacts' => 'CO',
                'purchase_payment' => 'PP',
                'sell_payment' => 'SP',
                'expense_payment' => null,
                'business_location' => 'BL',
                'username' => null,
                'subscription' => null,
            ]),
            'theme_color' => 'black-light',
            'created_by' => 1,
            'email_settings' => json_encode([
                'mail_driver' => 'smtp',
                'mail_host' => null,
                'mail_port' => null,
                'mail_username' => null,
                'mail_password' => null,
                'mail_encryption' => null,
                'mail_from_address' => null,
                'mail_from_name' => null,
            ]),
            'sms_settings' => json_encode([
                'url' => null,
                'send_to_param_name' => 'to',
                'msg_param_name' => 'text',
                'request_method' => 'post',
                'param_1' => null,
                'param_val_1' => null,
                'param_2' => null,
                'param_val_2' => null,
                'param_3' => null,
                'param_val_3' => null,
                'param_4' => null,
                'param_val_4' => null,
                'param_5' => null,
                'param_val_5' => null,
                'param_6' => null,
                'param_val_6' => null,
                'param_7' => null,
                'param_val_7' => null,
                'param_8' => null,
                'param_val_8' => null,
                'param_9' => null,
                'param_val_9' => null,
                'param_10' => null,
                'param_val_10' => null,
            ]),
            'is_active' => 1,
            'created_at' => Carbon::create('2022', '01', '16', '02', '12', '08'),
            'updated_at' => Carbon::create('2024', '08', '18', '12', '02', '14'),
        ]);

        // Seeder para la tabla users
        DB::table('users')->insert([
            'surname' => 'Sr',
            'first_name' => 'Administrador',
            'last_name' => '',
            'username' => 'admin',
            'email' => 'admin@admin.com',
            'password' => bcrypt('secret'),
            'language' => 'es',
            'contact_no' => null,
            'address' => null,
            'remember_token' => "YeYmRxETidnxeXiXXgwhiaJgZkvxH6foyCGwOsDjbL3jPWhQIm80tzWugyKp",
            'business_id' => 1,
            'status' => 'active',
            'is_cmmsn_agnt' => 0,
            'cmmsn_percent' => 0.00,
            'selected_contacts' => 0,
            'dob' => null,
            'marital_status' => null,
            'blood_group' => null,
            'contact_number' => null,
            'fb_link' => null,
            'twitter_link' => null,
            'social_media_1' => null,
            'social_media_2' => null,
            'permanent_address' => null,
            'current_address' => null,
            'guardian_name' => null,
            'custom_field_1' => null,
            'custom_field_2' => null,
            'custom_field_3' => null,
            'custom_field_4' => null,
            'bank_details' => json_encode([
                'account_holder_name' => null,
                'account_number' => null,
                'bank_name' => null,
                'bank_code' => null,
                'branch' => null,
                'tax_payer_id' => null,
            ]),
            'id_proof_name' => null,
            'id_proof_number' => null,
            'deleted_at' => null,
            'created_at' => Carbon::create('2022', '01', '16', '02', '12', '08'),
            'updated_at' => Carbon::create('2022', '03', '15', '13', '35', '03'),
        ]);

        // Seeder para la tabla system
        DB::table('system')->insert([
            ['key' => 'db_version', 'value' => '2.14.3'],
            ['key' => 'default_business_active_status', 'value' => '1'],
        ]);

        // Seeder para la tabla roles
        DB::table('roles')->insert([
            [
                'name' => 'Admin#1',
                'guard_name' => 'web',
                'business_id' => 1,
                'is_default' => 1,
                'is_service_staff' => 0,
                'created_at' => Carbon::create('2022', '01', '16', '02', '12', '08'),
                'updated_at' => Carbon::create('2022', '01', '16', '02', '12', '08'),
            ],
            [
                'name' => 'Cashier#1',
                'guard_name' => 'web',
                'business_id' => 1,
                'is_default' => 0,
                'is_service_staff' => 0,
                'created_at' => Carbon::create('2022', '01', '16', '02', '12', '08'),
                'updated_at' => Carbon::create('2022', '01', '16', '02', '12', '08'),
            ],
            [
                'name' => 'Vendedor#1',
                'guard_name' => 'web',
                'business_id' => 1,
                'is_default' => 0,
                'is_service_staff' => 0,
                'created_at' => Carbon::create('2024', '04', '30', '11', '54', '30'),
                'updated_at' => Carbon::create('2024', '04', '30', '11', '54', '30'),
            ],
            [
                'name' => 'Repartidor#1',
                'guard_name' => 'web',
                'business_id' => 1,
                'is_default' => 0,
                'is_service_staff' => 0,
                'created_at' => Carbon::create('2024', '07', '29', '11', '53', '36'),
                'updated_at' => Carbon::create('2024', '08', '06', '13', '21', '58'),
            ],
        ]);

        DB::table('model_has_roles')->insert([
            'role_id' => 1,
            'model_id' => 1,
            'model_type' => 'App\\User',
        ]);

        DB::table('role_has_permissions')->insert([
            ['permission_id' => 2, 'role_id' => 2],
            ['permission_id' => 8, 'role_id' => 2],
            ['permission_id' => 9, 'role_id' => 2],
            ['permission_id' => 10, 'role_id' => 2],
            ['permission_id' => 16, 'role_id' => 2],
            ['permission_id' => 38, 'role_id' => 2],
            ['permission_id' => 39, 'role_id' => 2],
            ['permission_id' => 40, 'role_id' => 2],
            ['permission_id' => 41, 'role_id' => 2],
            ['permission_id' => 2, 'role_id' => 3],
            ['permission_id' => 6, 'role_id' => 3],
            ['permission_id' => 9, 'role_id' => 3],
            ['permission_id' => 10, 'role_id' => 3],
            ['permission_id' => 17, 'role_id' => 3],
            ['permission_id' => 18, 'role_id' => 3],
            ['permission_id' => 26, 'role_id' => 3],
            ['permission_id' => 27, 'role_id' => 3],
            ['permission_id' => 28, 'role_id' => 3],
            ['permission_id' => 30, 'role_id' => 3],
            ['permission_id' => 34, 'role_id' => 3],
            ['permission_id' => 53, 'role_id' => 3],
            ['permission_id' => 61, 'role_id' => 3],
            ['permission_id' => 72, 'role_id' => 3],
            ['permission_id' => 2, 'role_id' => 4],
            ['permission_id' => 8, 'role_id' => 4],
            ['permission_id' => 39, 'role_id' => 4],
            ['permission_id' => 40, 'role_id' => 4],
            ['permission_id' => 70, 'role_id' => 4],
            ['permission_id' => 75, 'role_id' => 4],
            ['permission_id' => 77, 'role_id' => 4],
            ['permission_id' => 78, 'role_id' => 4],
            ['permission_id' => 83, 'role_id' => 4],
            ['permission_id' => 84, 'role_id' => 4],
            ['permission_id' => 85, 'role_id' => 4],
            ['permission_id' => 86, 'role_id' => 4],
        ]);
    }
}
