@extends('layouts.app')
@section('title', 'Terminos y condiciones')

@section('content')

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="row">
        <div class="col-xs-6">
            <h1>Terminos y condiciones
            </h1>
        </div>
        <div class="col-xs-6">
            <a href="uploads/TÉRMINOS_Y_CONDICIONES_DE_USO_DE_BIT_ERP.pdf" type="button" class="btn btn-primary pull-right" download
            ><i class="fa fa-download"></i> Descargar</a>
        </div>
    </div>
</section>

<!-- Main content -->
<section class="content">
    <br>
    <div class="row">
        <div class="col-xs-12">
                @component('components.widget')
                <div style="margin: 0px 0px 0px 80px; width: 80%;">
                    <br>
                    <p><strong><span style="font-size: 18px;">Informaci&oacute;n general</span></strong></p>
                    <p><span style="font-size: 18px;">Los presentes T&eacute;rminos y Condiciones son aplicables al registro y uso de la Aplicaci&oacute;n Web Bit ERP (en adelante, la Aplicaci&oacute;n Web) por parte de un usuario (en adelante el/los &ldquo;Usuario/s&rdquo;) indica la aceptaci&oacute;n absoluta de los presentes T&eacute;rminos y Condiciones y de la Pol&iacute;tica de Privacidad.</span></p>
                    <p><span style="font-size: 18px;">Estos T&eacute;rminos y Condiciones de Uso regulan las reglas a que se sujeta la utilizaci&oacute;n de la Aplicaci&oacute;n Web, que puede accederse desde cualquier navegador web o utilizarse en la direcci&oacute;n web sistemaerp.com.ar.</span></p>
                    <p><span style="font-size: 18px;">El acceso o utilizaci&oacute;n de la Aplicaci&oacute;n Web atribuye la condici&oacute;n de Usuario a quien lo haga e implica la aceptaci&oacute;n de todas las condiciones incluidas en este documento y en la Pol&iacute;tica de Privacidad.</span></p>
                    <p><span style="font-size: 18px;">El Usuario deber&iacute;a leer estas condiciones cada vez que utilice la Aplicaci&oacute;n Web, ya que podr&iacute;an ser modificadas en lo sucesivo.</span></p>
                    <p><span style="font-size: 18px;">El acceso a la Aplicaci&oacute;n Web es restringida a usuarios que abonan por su utilizaci&oacute;n.</span></p>
                    <p><span style="font-size: 18px;">El Usuario garantiza y declara ser mayor de 18 a&ntilde;os, y/o en su caso, que tiene la expresa autorizaci&oacute;n de sus padres o de sus tutores para poder acceder al sitio web y que es competente para entender y aceptar sin reservas las obligaciones, afirmaciones, representaciones y garant&iacute;as establecidas en estos T&eacute;rminos y Condiciones. Por su parte, Bitecnolog&iacute;as, en adelante &ldquo;el Administrador&rdquo;, deslinda su responsabilidad en el caso de no ser veraz la informaci&oacute;n suministrada al respecto. El Usuario deber&aacute; respetar estos T&eacute;rminos y Condiciones de Uso de la aplicaci&oacute;n web. Las infracciones por acci&oacute;n u omisi&oacute;n de los presentes T&eacute;rminos y Condiciones de Uso generar&aacute;n el derecho a favor del Administrador de suspender al Usuario que las haya realizado.</span></p>
                    <p><span style="font-size: 18px;">El Usuario se obliga a usar los Servicios Digitales de conformidad con estos T&eacute;rminos y Condiciones, en forma correcta y l&iacute;cita. En caso contrario, el Administrador podr&aacute; suspender la cuenta del Usuario, por considerarlo: violatorio de estos T&eacute;rminos y Condiciones y/o de la Pol&iacute;tica de Privacidad de estos Servicios Digitales, ofensivo, ilegal, violatorio de derechos de terceros, contrario a la moral y buenas costumbres y amenaza la seguridad de otros Usuarios. Sin embargo, esta posibilidad no implica necesariamente que el contenido de toda la informaci&oacute;n disponible en los Servicios Digitales haya sido revisado. El Usuario se compromete a: No acceder a datos restringidos o a intentar violar las barreras de seguridad para llegar a ellos. No realizar b&uacute;squedas de vulnerabilidades o explotaci&oacute;n de las mismas para cualquier fin. No divulgar informaci&oacute;n acerca de la detecci&oacute;n de vulnerabilidades encontradas en los Servicios Digitales. Comunicar al Administrador toda informaci&oacute;n a la que tenga acceso que pudiera implicar un compromiso a la seguridad de la informaci&oacute;n o los servicios digitales. La adecuada utilizaci&oacute;n de todos los recursos de Internet es, sin excepci&oacute;n, de entera responsabilidad del Usuario de la Aplicaci&oacute;n Web.</span></p>
                    <p><span style="font-size: 18px;"><strong>Cargos</strong></span></p>
                    <p><span style="font-size: 18px;">El uso de la Aplicaci&oacute;n Web implica un costo mensual. Los cargos por el uso del software se aplicar&aacute;n desde el 1 al 10 de cada mes, por adelantado. Una vez realizado el pago, no se podr&aacute; requerir devoluci&oacute;n por uso descontinuado ni concluir con antelaci&oacute;n su uso.&nbsp;</span></p>
                    <p><span style="font-size: 18px;">El usuario es el responsable del pago de todos los costos o gastos en los que incurras como resultado de utilizar la Aplicaci&oacute;n Web, incluidos los cargos de red del operador o de itinerancia. Consulta con tu proveedor de servicios los detalles al respecto.</span></p>
                    <p><span style="font-size: 18px;">Estad&iacute;sticas an&oacute;nimas Bitecnologias se reserva el derecho a realizar un seguimiento de tu actividad en la Aplicaci&oacute;n Web y a informar de ello a nuestros proveedores de servicios estad&iacute;sticos de terceros. Todo ello de forma an&oacute;nima.</span></p>
                    <p><span style="font-size: 18px;"><strong>Tu informaci&oacute;n</strong></span></p>
                    <p><span style="font-size: 18px;">Protecci&oacute;n de tu informaci&oacute;n personal: queremos ayudarte a llevar a cabo todos los pasos necesarios para proteger tu privacidad e informaci&oacute;n. Consulta la Pol&iacute;tica de privacidad de Bitecnologias y los avisos sobre privacidad de la Aplicaci&oacute;n Web para conocer qu&eacute; tipo de informaci&oacute;n recopilamos y las medidas que tomamos para proteger tu informaci&oacute;n personal.</span></p>
                    <p><span style="font-size: 18px;">El titular de los datos personales podr&aacute; solicitar la actualizaci&oacute;n, rectificaci&oacute;n y, cuando corresponda, la supresi&oacute;n o el sometimiento a confidencialidad de los datos personales provistos, pudiendo acceder en forma gratuita, a intervalos no inferiores a seis meses, a la Base de datos habilitada, la cual se encuentra debidamente inscripta por la Disposici&oacute;n 9 &ndash; E/2016, de la Subsecretar&iacute;a de Gobierno Digital, parte de la Secretar&iacute;a de Gesti&oacute;n e Innovaci&oacute;n P&uacute;blica, del Ministerio de Modernizaci&oacute;n en los t&eacute;rminos de la Ley de Protecci&oacute;n de Datos Personales, N&ordm; 25.326, y sus normas complementarias, salvo que se acredite un inter&eacute;s leg&iacute;timo a tal fin, conforme lo establecido en el art&iacute;culo 14, inciso 3 de la Ley N&deg; 25.326. La Direcci&oacute;n Nacional de Protecci&oacute;n de Datos Personales, &oacute;rgano de control de la Ley N&deg; 25.326, tiene la atribuci&oacute;n de atender las denuncias y reclamos que se formulen con relaci&oacute;n al incumplimiento de las normas sobre protecci&oacute;n de datos personales.</span></p>
                    <p><span style="font-size: 18px;">Los datos recolectados tendr&aacute;n por finalidad: Optimizar los servicios brindados por Bitecnologias. Compararlos con los registros de los servicios de Bitecnologias para ofrecer informaciones relevantes al Usuario. Enviar a las personas alertas por SMS o e-mail, respecto a los servicios utilizados y sobre los cuales solicit&oacute; dichas notificaciones como, por ejemplo, un mensaje sin leer.</span></p>
                    <p><span style="font-size: 18px;">Personalizar el contenido visualizado por el Usuario de la Aplicaci&oacute;n Web. Obtener m&eacute;tricas de uso y niveles de servicio de la Aplicaci&oacute;n Web.</span></p>
                    <p><span style="font-size: 18px;"><strong>Prohibiciones</strong></span></p>
                    <p><span style="font-size: 18px;">Queda prohibido alterar o modificar ninguna parte de la Aplicaci&oacute;n Web o de los contenidos de la misma, eludir, desactivar o manipular de cualquier otra forma (o tratar de eludir, desactivar o manipular) las funciones de seguridad u otras funciones del programa.</span></p>
                    <p><span style="font-size: 18px;">Queda prohibido el uso de la Aplicaci&oacute;n Web con la finalidad de lesionar bienes, derechos o intereses de Bitecnologias o de terceros. Queda igualmente prohibido realizar cualquier otro uso que altere, da&ntilde;e o inutilice las redes, servidores, equipos, productos y programas inform&aacute;ticos de Bitecnologias o de terceros. Las siguientes actividades se encuentran expresamente vedadas, sin perjuicio de las prohibiciones generales expuestas anteriormente: Hostigar, acosar, amenazar, acechar, realizar actos de vandalismo hacia otros Usuarios. Infringir los derechos a la intimidad de otros Usuarios. Solicitar informaci&oacute;n personal identificable de otros Usuarios con el prop&oacute;sito de hostigar, atacar, explotar, violar la intimidad de los mismos; Publicar de manera intencionada o con conocimiento injurias o calumnias; Publicar, con el intento de enga&ntilde;ar, contenido que es falso o inexacto; Intentar usurpar la identidad de otro Usuario, representando de manera falsa su afiliaci&oacute;n con cualquier individuo o entidad, o utilizar el nombre de otro Usuario con el prop&oacute;sito de enga&ntilde;ar; Promover, defender o mostrar pornograf&iacute;a, obscenidad, vulgaridad, blasfemia, odio, fanatismo, racismo y/o violencia. Vulnerar los derechos establecidos en la Ley N&deg; 25.326 de Protecci&oacute;n de Datos Personales. En caso de sufrir alguna de estas situaciones, deber&aacute; comunicarse con el Administrador a trav&eacute;s de <a data-fr-linked="true" href="mailto:contacto@bitecnologias.com">contacto@bitecnologias.com</a>.</span></p>
                    <p><span style="font-size: 18px;">La informaci&oacute;n personal suministrada por el Usuario al momento de inscribirse en el sitio web est&aacute; protegida con una clave y s&oacute;lo podr&aacute; ser modificada por el mismo Usuario.</span></p>
                    <p><span style="font-size: 18px;">Bitecnolog&iacute;as se reserva el derecho de realizar validaciones en relaci&oacute;n a la informaci&oacute;n brindada por el Usuario al momento de la inscripci&oacute;n. En caso de que la informaci&oacute;n brindada no pueda validarse, el Administrador se reserva el derecho de no dar de alta a ese Usuario. Al momento de la inscripci&oacute;n, el Usuario asume el compromiso y la responsabilidad de: No proporcionar informaci&oacute;n personal falsa ni crear cuentas a nombre de terceros. No crear m&aacute;s de una cuenta personal. No crear otra cuenta sin permiso expreso del Administrador, en caso de que este &uacute;ltimo haya inhabilitado la cuenta original. Mantener la informaci&oacute;n de contacto exacta y actualizada. No compartir la contrase&ntilde;a ni permitir a otra persona acceda a su cuenta. El Usuario se compromete a notificar al Administrador ante cualquier uso no autorizado de su clave. El Administrador se reserva el derecho de rechazar cualquier solicitud de inscripci&oacute;n o de cancelar un registro previamente aceptado.</span></p>
                    <p><span style="font-size: 18px;"><strong>Propiedad</strong></span></p>
                    <p><span style="font-size: 18px;">La Aplicaci&oacute;n Web, la expresi&oacute;n de ideas, procedimientos, m&eacute;todos de operaci&oacute;n y conceptos matem&aacute;ticos de conformidad con lo establecido en el art&iacute;culo 1&ordm; de la Ley 11.723 y sus modificatorias, as&iacute; como los textos, fotograf&iacute;as, gr&aacute;ficos, im&aacute;genes, tecnolog&iacute;a, software, links, contenidos, dise&ntilde;o gr&aacute;fico, c&oacute;digo fuente, etc., as&iacute; como las marcas y dem&aacute;s signos distintivos son propiedad de Bitecnologias o de terceros, no adquiriendo el Usuario ning&uacute;n derecho sobre ellos por el mero uso de la Aplicaci&oacute;n Web. El Usuario, deber&aacute; abstenerse de:</span></p>
                    <p><span style="font-size: 18px;">a) Reproducir, copiar, distribuir, poner a disposici&oacute;n de terceros, comunicar p&uacute;blicamente, transformar o modificar la Aplicaci&oacute;n Web o sus contenidos, salvo en los casos contemplados en la ley o expresamente autorizados por Bitecnologias o por el titular de dichos derechos.</span></p>
                    <p><span style="font-size: 18px;">b) Reproducir o copiar para uso privado la Aplicaci&oacute;n Web o sus contenidos, as&iacute; como comunicarlos p&uacute;blicamente o ponerlos a disposici&oacute;n de terceros cuando ello conlleve su reproducci&oacute;n.</span></p>
                    <p><span style="font-size: 18px;">c) Extraer o reutilizar todo o parte sustancial de los contenidos integrantes de la Aplicaci&oacute;n Web.</span></p>
                    <p><span style="font-size: 18px;"><strong>Da&ntilde;os</strong></span></p>
                    <p><span style="font-size: 18px;">Corresponde al Usuario, en todo caso, disponer de herramientas adecuadas para la detecci&oacute;n y desinfecci&oacute;n de programas maliciosos o cualquier otro elemento inform&aacute;tico da&ntilde;ino. Bitecnologias no se responsabiliza de los da&ntilde;os producidos a equipos inform&aacute;ticos durante el uso de la Aplicaci&oacute;n Web. Igualmente, Bitecnologias no ser&aacute; responsable de los da&ntilde;os producidos a los Usuarios cuando dichos da&ntilde;os tengan su origen en fallos o desconexiones en las redes de telecomunicaciones que interrumpan el servicio.</span></p>
                    <p><span style="font-size: 18px;"><strong>Actualizaciones de los TyC</strong></span></p>
                    <p><span style="font-size: 18px;">IMPORTANTE: Podemos, sin que esto suponga ninguna obligaci&oacute;n con el Usuario, modificar estas Condiciones de uso sin avisar en cualquier momento. Si el Usuario contin&uacute;a utilizando la aplicaci&oacute;n una vez realizada cualquier modificaci&oacute;n en estas Condiciones de uso, esa utilizaci&oacute;n continuada constituir&aacute; la aceptaci&oacute;n por tu parte de tales modificaciones.</span></p>
                    <p><span style="font-size: 18px;">Si no se aceptan estas condiciones de uso ni se acepta quedar sujeto a ellas, el usuario no debe utilizar la aplicaci&oacute;n ni descargar o utilizar cualquier software relacionado. El uso que se haga de la aplicaci&oacute;n queda bajo la &uacute;nica responsabilidad del Usuario. Bitecnolog&iacute;as no tiene responsabilidad alguna por la eliminaci&oacute;n o la incapacidad de almacenar o transmitir cualquier contenido u otra informaci&oacute;n mantenida o transmitida por la aplicaci&oacute;n. No somos responsables de la precisi&oacute;n o la fiabilidad de cualquier informaci&oacute;n o consejo transmitidos a trav&eacute;s de la aplicaci&oacute;n. Podemos, en cualquier momento, limitar o interrumpir el uso a nuestra &uacute;nica discreci&oacute;n. Hasta el m&aacute;ximo que permite la ley, en ning&uacute;n caso seremos responsables por cualquier p&eacute;rdida o da&ntilde;o relacionados.</span></p>
                    <p><span style="font-size: 18px;"><strong>Compromiso de uso</strong></span></p>
                    <p><span style="font-size: 18px;">El Usuario se compromete a hacer un uso correcto de la Aplicaci&oacute;n Web, de conformidad con la Ley, con los presentes T&eacute;rminos y Condiciones de Uso y con las dem&aacute;s reglamentos e instrucciones que, en su caso, pudieran ser de aplicaci&oacute;n.</span></p>
                    <p><span style="font-size: 18px;">El Usuario responder&aacute; frente a Bitecnologias y frente a terceros de cualesquiera da&ntilde;os o perjuicios que pudieran causarse por incumplimiento de estas obligaciones.</span></p>
                    <p><span style="font-size: 18px;"><strong>Disputas</strong></span></p>
                    <p><span style="font-size: 18px;">Estos T&eacute;rminos y Condiciones de Uso se rigen &iacute;ntegramente por la legislaci&oacute;n argentina.</span></p>
                    <p><span style="font-size: 18px;">Para la resoluci&oacute;n de cualquier conflicto relativo a su interpretaci&oacute;n o aplicaci&oacute;n, el Usuario se somete expresamente a la jurisdicci&oacute;n de los Tribunales Nacionales en lo Contencioso Administrativo</span></p>
                </div>
                @endcomponent
        </div>
    </div>

   


</section>
<!-- /.content -->
@stop